--핸드폰 테이블명 : TBL_PHONE
--PHONE_SERIAL_NUMBER NUMBER : PRIMARY KEY
-----------------------------------------
--PHONE_COLOR VARCHAR2(100),
--PHONE_SIZE VARCHAR2(100),
--PHONE_PRICE NUMBER,
--PHONE_PRODUCTION_DATE DATE,
--PHONE_SALE NUMBER
--
--
--핸드폰케이스 테이블명 : TBL_PHONE_CASE
--CASE_SERIAL_NUMBER NUMBER : PRIMARY KEY
-----------------------------------------
--CASE_COLOR VARCHAR2(100),
--CASE_PRICE NUMBER,
--PHONE_SERIAL_NUMBER NUMBER : FOREIGN KEY

DROP TABLE TBL_PHONE_CASE;

CREATE TABLE TBL_PHONE(
	PHONE_SERIAL_NUMBER NUMBER,
	PHONE_COLOR VARCHAR2(100),
	PHONE_SIZE VARCHAR2(100),
	PHONE_PRICE NUMBER,
	PHONE_PRODUCTION_DATE DATE,
	PHONE_SALE NUMBER,
	-- PK제약조건 추가하기
	CONSTRAINT PK_PHONE_SERIAL_NUMBER PRIMARY KEY(PHONE_SERIAL_NUMBER)
);

CREATE TABLE TBL_PHONE_CASE(
	CASE_SERIAL_NUMBER NUMBER,
	CASE_COLOR VARCHAR2(100),
	CASE_PRICE NUMBER,
	PHONE_SERIAL_NUMBER NUMBER,
	-- PK 제약조건 추가하기
	CONSTRAINT PK_CASE PRIMARY KEY(CASE_SERIAL_NUMBER),
	-- FK 제약조건 추가하기
	CONSTRAINT FK_CASE FOREIGN KEY(PHONE_SERIAL_NUMBER) REFERENCES TBL_PHONE(PHONE_SERIAL_NUMBER)
	);






SELECT * FROM TBL_PHONE;
SELECT * FROM TBL_PHONE_CASE;
