-- 5번 : DML(데이터 조작어) 기초

-- 테이블 생성(DDL)
CREATE TABLE TBL_MEMBER(
	MEMBER_ID NUMBER,
	NUMBER_NAME VARCHAR2(100),
	MEMBER_AGE NUMBER(3)
);

-- 데이터 추가
/* INSERT INTO 테이블명
 * VALUES (값1, 값2, 값3); */
INSERT INTO TBL_MEMBER
VALUES (1, '강버들', 25);

INSERT INTO TBL_MEMBER(MEMBER_ID, NUMBER_NAME)
VALUES (2, '홍길동');

INSERT INTO TBL_MEMBER
VALUES (3, '짱구', NULL);

-- 데이터 조회
SELECT * FROM TBL_MEMBER;

SELECT * 
FROM TBL_MEMBER
WHERE NUMBER_NAME = '홍길동';

-- 데이터 삭제
--DELETE FROM 테이블명
DELETE FROM TBL_MEMBER
WHERE NUMBER_NAME = '홍길동';

INSERT INTO TBL_MEMBER
VALUES(4, '철수', 5);

INSERT INTO TBL_MEMBER
VALUES (5, '유리', 5);

INSERT INTO TBL_MEMBER VALUES (6, '훈이', 5);

-- 수정
/*UPDATE 테이블명 SET 컬럼명=값
WHERE 조건식;*/

UPDATE TBL_MEMBER
SET MEMBER_AGE = 5;

SELECT * FROM TBL_MEMBER;

-- MEMBER_ID가 1인 값을 20으로 변경
UPDATE TBL_MEMBER
SET MEMBER_AGE=20
WHERE MEMBER_ID = 1;

-- 두번째 테이블 생성(TBL_STUDENT)
CREATE TABLE TBL_STUDENT(
	STUDENT_NUMBER NUMBER,
	STUDENT_NAME VARCHAR2(100),
	STUDENT_MATH NUMBER,
	STUDENT_ENG NUMBER,
	STUDENT_KOR NUMBER,
	STUDENT_GRADE VARCHAR2(100)
);

-- 테이블 삭제
--DROP TABLE TBL_STUDENT;

SELECT * FROM TBL_STUDENT;

/*학생 테이블에 데이터 추가~
 * 학생번호 이름 수학 영어 국어
 * 1	  짱구 90	  90  90
 * 2	  유리 70  25  55
 * 3	  맹구 40  100  70
 * 4	  훈이 100  15  20
 * */


INSERT INTO TBL_STUDENT
VALUES(0, '김철수', 100,100,100, 'A+');

INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH, STUDENT_ENG, STUDENT_KOR)
VALUES(1, '짱구', 90, 90, 90);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH, STUDENT_ENG, STUDENT_KOR)
VALUES(2, '유리', 70, 25, 55);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH, STUDENT_ENG, STUDENT_KOR)
VALUES(3, '맹구', 40, 100, 70);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH, STUDENT_ENG, STUDENT_KOR)
VALUES(4, '훈이', 100, 15, 20);

SELECT * FROM TBL_STUDENT;











